---

- name: install bind9 package
  apt: 
    name: bind9
    state: latest
    update_cache: no

- name: create zonefile backup directory
  file:
    path: /etc/bind/backup
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create bind log directory
  file:
    path: /var/log/named
    state: directory
    owner: bind
    group: bind
    mode: 0755

- name: create bind query log
  file:
    path: /var/log/named/query.log
    state: touch
    owner: bind
    group: bind
    mode: 0644
  changed_when: false

- name: copy named.conf files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  with_items:
    - named.conf
    - named.conf.default-zones
    - named.conf.scale-zones
    - named.conf.scale-ip-zones
    - named.conf.options
    - db.scale.lan.records.routers

- name: copy scale view, record, and acl files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/{{ item }}"
    owner: root
    group: bind
    mode: 0644
  register: records
  with_items:
    - db.scale.lan.records.servers
    - db.scale.lan.records.switches
    - db.scale.lan.records.conference
    - db.scale.lan.records.expo
    - db.ip6.arpa.records
    - db.10.ip4.arpa.records
    - db.scale.lan
    - named.conf.scale-acls

- name: generate zone serial number
  shell: date +%y%m%d%H%M
  register: date
  when: records.changed 

- name: set fact zone serial
  set_fact:
    bind_zone_serial: "{{ date.stdout }}"
  when: records.changed

- name: copy scale conference view files
  template:
    src: db.scale.lan.conference.j2
    dest: "{{ item }}"
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  when: records.changed
  with_items:
    - /etc/bind/db.scale.lan.conference
    - /etc/bind/backup/db.scale.lan.conference.{{ bind_zone_serial }}

- name: copy scale expo view files
  template:
    src: db.scale.lan.expo.j2
    dest: "{{ item }}"
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  when: records.changed
  with_items:
    - /etc/bind/db.scale.lan.expo
    - /etc/bind/backup/db.scale.lan.expo.{{ bind_zone_serial }}

- name: copy ip6 ptr zone files
  template:
    src: db.ip6.arpa.j2
    dest: "{{ item }}"
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  when: records.changed
  with_items:
    - /etc/bind/db.ip6.arpa
    - /etc/bind/backup/db.ip6.arpa.{{ bind_zone_serial }}

- name: copy ip4 ptr zone files
  template:
    src: db.10.ip4.arpa.j2
    dest: "{{ item }}"
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  when: records.changed
  with_items:
    - /etc/bind/db.10.ip4.arpa
    - /etc/bind/backup/db.10.ip4.arpa.{{ bind_zone_serial }}

- name: copy scale view, record, and acl backup files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/bind/backup/{{ item }}.{{ bind_zone_serial }}"
    owner: root
    group: bind
    mode: 0644
  when: records.changed
  with_items:
    - db.scale.lan.records.servers
    - db.scale.lan.records.switches
    - db.scale.lan.records.conference
    - db.scale.lan.records.expo
    - db.ip6.arpa.records
    - db.10.ip4.arpa.records
    - db.scale.lan
    - named.conf.scale-acls
  
- name: start bind9 service
  systemd: 
    name: bind9
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when: not records.changed
