---

- name: install bind9 package
  apt: 
    name: bind9
    state: present
  register: bind_new_install

- name: generate zone serial number
  shell: date +%y%m%d%H%M
  register: date
  changed_when: false

- name: set fact zone serial
  set_fact:
    bind_zone_serial: "{{ date.stdout }}"

- name: copy named.conf files
  copy:
    src: "{{ item }}"
    dest: /etc/bind/
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  with_items:
    - named.conf
    - named.conf.default-zones
    - named.conf.scale-zones

- name: create zonefile backup directory
  file:
    path: /etc/bind/backup
    state: directory
    mode: 0700

- name: copy scale zone files
  template:
    src: db.scale.lan.j2
    dest: "{{ item }}"
    owner: root
    group: bind
    mode: 0644
  notify: restart bind9
  with_items:
    - /etc/bind/db.scale.lan
    - /etc/bind/backup/db.scale.lan.{{ bind_zone_serial }}
  
- name: start bind9 service
  service: 
    name: bind9
    state: started
    enabled: yes
  when: not bind_new_install.changed