---

- name: install chrony package
  apt:
    name: chrony
    state: present
    update_cache: no

- name: Copy chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify: restart chrony
  register: config

- name: start chrony service
  systemd:
    name: chrony
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when: not config.changed
