---

- name: create tech group
  group:
    name: tech
    state: present
    gid: "900"

- include_tasks:
    file: users.yml
  with_items:
    - owen
    - rob
    - dlang
    - kyle
    - steveb

- name: create root remote_tmp
  file:
    path: /root/.ansible/tmp
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy tech team sudoers file
  copy:
    src: sudoers.tech
    dest: /etc/sudoers.d/tech
    owner: root
    group: root
    mode: 0440
