---

- name: create tech group
  group:
    name: tech
    state: present
    gid: "900"

- name: create tech team users
  user:
    name: "{{ item }}"
    home: "/home/{{ item }}"
    groups: tech
    shell: /bin/bash
  with_items:
    - owen
    - rob
    - dlang
    - kyle
    - steveb

- name: create root remote_tmp
  file:
    path: /root/.ansible/tmp
    state: directory
    owner: root
    group: root
    mode: 0700

# Owen's key is currently invalid

- name: copy tech team rsa keys
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '{{ inventory_dir }}/../facts/keys/{{ item }}_id_rsa.pub') }}"
  with_items:
    # - owen
    - rob
    - dlang
    - kyle
    - steveb

- name: copy tech team sudoers file
  copy:
    src: sudoers.tech
    dest: /etc/sudoers.d/tech
    owner: root
    group: root
    mode: 0440
