---

version: 2
jobs:

  validate_datafiles:
    docker:
    - image: kylerisse/ansible-tester@sha256:f6a9507ec1d7a2dd0570cd88cb19746840c4f97e7618f53158616b9e1f5a3618
    resource_class: small
    working_directory: ~/scale-network/facts
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: lint python files
        command: pylint *.py

    - run:
        name: data file unit tests
        command: pytest -vv

  ansible_tests:
    docker:
    - image: kylerisse/ansible-tester@sha256:f6a9507ec1d7a2dd0570cd88cb19746840c4f97e7618f53158616b9e1f5a3618
    resource_class: small
    working_directory: ~/scale-network/ansible
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: lint ansible playbook
        command: ansible-lint -x 403 -x 503 scale.yml

    - run:
        name: lint python files
        command: pylint *.py

    - run:
        name: python unit tests
        command: pytest -vv

    - run:
        name: validate properly formed json
        command: ./inventory.py | jq

workflows:
  version: 2
  test_all:
    jobs:
      - validate_datafiles
      - ansible_tests:
          requires:
            - validate_datafiles
