---

version: 2
jobs:

  gomplate_tests:
    docker:
    - image: hairyhenderson/gomplate:v3.2.0-alpine
    resource_class: medium
    working_directory: ~/scale-network/tests/unit/openwrt
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: install diffutils
        command: apk update && apk add diffutils

    # Netgear WNDR 3700v2, 3800, 3800ch configs
    - run:
        name: openwrt ar71xx golden file test
        command: sh -x test.sh -t ar71xx

    # TP-Link c2600 configs
    - run:
        name: openwrt ipq806x golden file test
        command: sh -x test.sh -t ipq806x

  validate_datafiles:
    docker:
    - image: kylerisse/ansible-tester@sha256:f6a9507ec1d7a2dd0570cd88cb19746840c4f97e7618f53158616b9e1f5a3618
    resource_class: small
    working_directory: ~/scale-network/facts
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: lint python files
        command: pylint *.py

    - run:
        name: data file unit tests
        command: pytest -vv

  ansible_tests:
    docker:
    - image: kylerisse/ansible-tester@sha256:f6a9507ec1d7a2dd0570cd88cb19746840c4f97e7618f53158616b9e1f5a3618
    resource_class: small
    working_directory: ~/scale-network/ansible
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: lint ansible playbook
        command: ansible-lint -x 403 -x 503 scale.yml

    - run:
        name: lint python files
        command: pylint *.py

    - run:
        name: python unit tests
        command: pytest -vv

    - run:
        name: validate properly formed json
        command: ./inventory.py | jq

  perl_lint:
    docker:
    - image: perl:5
    resource_class: medium
    working_directory: ~/scale-network
    steps:
    - checkout:
        path: ~/scale-network

    - run:
        name: compile switch-configuration
        # Make all warnings into errors so perl has a return thats not 0
        command: find ./switch-configuration/ -iname "*.pl" | xargs -i perl -Mstrict -Mdiagnostics -M'warnings FATAL=>q(all)' -cw {}

    - run:
        name: Set temp password
        # Make sure we set a password
        command: echo "scale" > ./facts/secrets/jroot_pw

    - run:
        name: run switch-configuration
        working_directory: ~/scale-network/switch-configuration/config
        # Make sure we set a password
        command: ./scripts/build_switch_configs.pl

workflows:
  version: 2
  test_all:
    jobs:
      - gomplate_tests
      - validate_datafiles
      - ansible_tests:
          requires:
            - validate_datafiles
      - perl_lint
