---

- name: install isc-dhcp-server package
  apt:
    name: isc-dhcp-server
    state: present
    update_cache: no

- name: copy dhcp rsyslog file
  copy:
    src: rsyslog.dhcp.conf
    dest: /etc/rsyslog.d/dhcp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog

- name: create dhcp subnets and hosts backup directory
  file:
    path: /etc/dhcp/backup
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy dhcp6 subnets files
  template:
    src: "{{ item }}.j2"
    dest: /etc/dhcp/{{ item }}
    owner: root
    group: root
    mode: 0644
  register: subnets6
  notify: restart isc-dhcp-server6
  with_items:
    - dhcpd6.conf.subnets
    - dhcpd6.conf.hosts

- name: copy dhcp4 subnets files
  template:
    src: "{{ item }}.j2"
    dest: /etc/dhcp/{{ item }}
    owner: root
    group: root
    mode: 0644
  register: subnets4
  notify: restart isc-dhcp-server
  with_items:
    - dhcpd.conf.subnets
    - dhcpd.conf.hosts

- name: set fact subnets and hosts timestamp
  set_fact:
    subnets_timestamp: "{{ ansible_date_time.epoch }}"
  when: subnets6.changed or subnets4.changed

- name: copy dhcp6 subnet file
  template:
    src: dhcpd6.conf.subnets.j2
    dest: /etc/dhcp/backup/dhcpd6.conf.subnets.{{ subnets_timestamp }}
    owner: root
    group: root
    mode: 0644
  when: subnets6.changed

- name: copy dhcp6 host file
  template:
    src: dhcpd6.conf.hosts.j2
    dest: /etc/dhcp/backup/dhcpd6.conf.hosts.{{ subnets_timestamp }}
    owner: root
    group: root
    mode: 0644
  when: subnets6.changed

- name: copy dhcp4 subnets backup file
  template:
    src: dhcpd.conf.subnets.j2
    dest: /etc/dhcp/backup/dhcpd.conf.subnets.{{ subnets_timestamp }}
    owner: root
    group: root
    mode: 0644
  when: subnets4.changed

- name: copy dhcp4 hosts backup file
  template:
    src: dhcpd.conf.hosts.j2
    dest: /etc/dhcp/backup/dhcpd.conf.hosts.{{ subnets_timestamp }}
    owner: root
    group: root
    mode: 0644
  when: subnets4.changed

- name: copy dhcpd6.conf
  copy:
    src: dhcpd6.conf
    dest: /etc/dhcp/dhcpd6.conf
    owner: root
    group: root
    mode: 0644
  register: config6
  notify: restart isc-dhcp-server6

- name: copy dhcpd.conf
  copy:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: 0644
  register: config4
  notify: restart isc-dhcp-server

- name: start isc-dhcp-server6 service
  systemd:
    name: isc-dhcp-server6
    state: started
    enabled: yes
    masked: no
    daemon_reload: no
  changed_when: false
  when: not config6.changed and subnets6.changed

- name: start isc-dhcp-server service
  systemd:
    name: isc-dhcp-server
    state: started
    enabled: yes
    masked: no
    daemon_reload: no
  changed_when: false
  when: not config4.changed and not subnets4.changed
