---

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
    masked: no

- name: restart isc-dhcp-server
  systemd:
    name: isc-dhcp-server
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes

- name: restart isc-dhcp-server6
  systemd:
    name: isc-dhcp-server6
    state: restarted
    enabled: yes
    masked: no
    daemon_reload: yes
