---

- name: copy resolved.conf
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: 0644
  notify: restart resolved
  register: resolved

- name: start resolved service
  systemd:
    name: systemd-resolved
    enabled: yes
    state: started
    masked: no
    daemon_reload: yes
  when: not resolved.changed
