---

- hosts: core
  become: yes
  serial: 1
  roles:
    - dnsserver
    - dhcpserver
    - zabbixagent

- hosts: core,automation,monitoring
  become: yes
  roles:
    - techteam
    - dnsclient
    - noapparmor
    - chrony

- hosts: automation
  become: yes
  roles:
    - signs
    - zabbixagent
    - xymon
