---

- name: install rsyslog package
  apt:
    name: rsyslog
    state: present
    update_cache: no



- name: start rsyslog service
  systemd:
    name: rsyslog
    enabled: yes
    state: started
    masked: no
    daemon_reload: no

