---

- name: restart apache
  systemd:
    name: apache2
    state: restarted
    enabled: yes
    masked: no

- name: restart xymon
  systemd:
    name: xymon
    state: restarted
    enabled: yes
    masked: no
