---

- hosts: all
  become: yes
  roles:
    - { role: noapparmor }

- hosts: core
  become: yes 
  roles: 
    # to be replaced with bind
    #- { role: dnsserver }
    - { role: dhcpserver }
    - { role: syslogserver }