---

- hosts: servers
  become: yes
  serial: 1
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - aptupdate

- hosts: core
  become: yes
  serial: 1
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - dnsserver
    - dhcpserver

- hosts: servers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - python27
    - techteam
    - dnsclient
    - noapparmor
    - chrony

- hosts: automation
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - signs
