---
name: openwrt-golden

on:
  pull_request:
    paths:
      - 'openwrt/**'
      - 'facts/**'
      - 'tests/**'
  push:   # This is only run when PRs are merged into master
    branches:
      - master
  workflow_dispatch:


jobs:
  gomplate_tests:
    name: gomplate_tests
    runs-on: ubuntu-latest
    container:
      # gomplate v3.2.0-alpine
      image: hairyhenderson/gomplate@sha256:7614155c5c6ce3fa8ac892e2e77643615bd8724d2b9c9817037540f324af2342
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: install_diffutils
        id: diffutils
        shell: bash
        run: |
          apk update && apk add diffutils
      - name: openwrt_golden_ar71xx
        shell: bash
          cd tests/unit/openwrt
          bash -x test.sh -t ar71xx
      - name: openwrt_golden_ipq806x
        shell: bash
          cd tests/unit/openwrt
          bash -x test.sh -t ipq806x
