---
name: openwrt-golden

on:
  pull_request:
    paths:
      - '.github/**'
      - 'openwrt/**'
      - 'facts/**'
      - 'tests/**'
  push:   # This is only run when PRs are merged into master
    branches:
      - master
  workflow_dispatch:


jobs:
  gomplate_tests:
    name: gomplate_tests
    runs-on: ubuntu-latest
    container:
      # gomplate v3.11.3-alpine
      image: hairyhenderson/gomplate@sha256:7a8e23a4900cb11b92b1e19122b7e20c606fb21d3fc569c44c3d9e7fc9cab1ee
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - name: install_diffutils
        id: diffutils
        shell: sh
        run: |
          apk update && apk add diffutils
      - name: openwrt_golden_ar71xx
        shell: sh
        run: |
          cd tests/unit/openwrt
          sh -x test.sh -t ar71xx
