---
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 3 * * 0'

jobs:
  build:
    name: Building openwrt img
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: ["ar71xx", "ipq806x"]
    container:
      image: sarcasticadmin/openwrt-build@sha256:bab6de3f66f5365d866de646bb9fd1f2000061d1a5fe8a07b6a714661a9a9a63
      # Since user is openwrt and gets 1001 from inside container
      options: --user 1001
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ env.BRANCH }}
      - name: 'Build openwrt'
        run: |
          cd openwrt
          TARGET=${{ matrix.target }} make templates build-img package 2>&1 | tee ${{ matrix.target }}-build.log
      - name: 'Upload openwrt build artifact tarball'
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ matrix.target }}-openwrt-build-artifacts
          # Cant use relative pathing .. or . for artifacts action
          # Also dont bother with '${{ github.workspace }}'
          path: |
            openwrt/build/artifacts/*.tar.gz
          retention-days: 30
      - name: 'Upload openwrt build log'
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ matrix.target }}-openwrt-buildlog
          path: |
            openwrt/*build.log
          retention-days: 30
