---

- name: install apache
  apt:
    name: [ apache2, xymon, fping ]
    state: present

- name: copy xymon apache conf
  copy:
    src: xymon.conf
    dest: /etc/apache2/conf-available/xymon.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: copy apache default config
  copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: copy apache ports config
  copy:
    src: ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: copy xymon server config
  copy:
    src: xymonserver.cfg
    dest: /etc/xymon/xmonserver.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart xymon

- name: copy xymon hosts config
  template:
    src: hosts.cfg.j2
    dest: /etc/xymon/hosts.cfg
    owner: root
    group: root
    mode: 0644
  notify: restart xymon
